In [1]:
import numpy as np

In [2]:
import sys
import os

sys.path.append(os.path.abspath(os.path.join('..')))

In [3]:
from NN.Layers.Dense import Dense
from NN.Activations.Sigmoid import Sigmoid
from NN.LossFunctions.MSE import MSE
from NN.Networks.Sequential import Sequential

In [4]:
## XOR Data
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
X = X.reshape(4, 2, 1)
print(X)
print()

y = np.array([[0],
              [1],
              [1],
              [0]])
y = y.reshape(4, 1, 1)
print(y)

[[[0]
  [0]]

 [[0]
  [1]]

 [[1]
  [0]]

 [[1]
  [1]]]

[[[0]]

 [[1]]

 [[1]]

 [[0]]]


In [5]:
xor_model = Sequential([
        Dense(2, 3),
        Sigmoid(),
        Dense(3, 1),
        Sigmoid()
    ],
    loss_fn=MSE())

In [6]:
xor_model.train(X, y, epochs=10000, lr=0.1)

Completed 1/10000 epoch, loss = 0.17632850953302753
Completed 2/10000 epoch, loss = 0.17423776566986082
Completed 3/10000 epoch, loss = 0.17214473394028043
Completed 4/10000 epoch, loss = 0.17005380061404424
Completed 5/10000 epoch, loss = 0.16796946880166927
Completed 6/10000 epoch, loss = 0.16589631388239312
Completed 7/10000 epoch, loss = 0.16383893557246304
Completed 8/10000 epoch, loss = 0.1618019076931149
Completed 9/10000 epoch, loss = 0.15978972684009318
Completed 10/10000 epoch, loss = 0.15780676125144555
Completed 11/10000 epoch, loss = 0.15585720120903865
Completed 12/10000 epoch, loss = 0.15394501228686086
Completed 13/10000 epoch, loss = 0.15207389267499885
Completed 14/10000 epoch, loss = 0.15024723566601844
Completed 15/10000 epoch, loss = 0.14846809819841061
Completed 16/10000 epoch, loss = 0.14673917612144954
Completed 17/10000 epoch, loss = 0.14506278659146243
Completed 18/10000 epoch, loss = 0.14344085774659698
Completed 19/10000 epoch, loss = 0.14187492555105152
Com

In [13]:
for x in X:
    print(xor_model.predict(x))

[[0.04156828]]
[[0.49483228]]
[[0.94039286]]
[[0.50216511]]
